name: Build PlatformIO project
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            targets: [ttgo-t-beam-sx1278, ttgo-t-beam-sx1276, ttgo-t-beam-sx1262, ttgo-t3-v1_3-sx1278, ttgo-t3-v1_3-sx1276, ttgo-t3-v1_6-sx1278, ttgo-t3-v1_6-sx1276]
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          
      - name: Pythine setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project for ${{ matrix.targets }}
        run: pio ci --environment ${{ matrix.targets }}